trigger:
- main  # Runs when pushing to main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

- script: |
    mvn clean install
  displayName: 'Build Java Project'

- script: |
    mvn test
  displayName: 'Run Unit Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureAppServiceConnection'
    appName: '<summer2020-b20-app>'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'
